site_name: Website
site_url: https://wijkqwe.github.io/
repo_url: https://github.com/Wijkqwe/Wijkqwe.github.io
remote_branch: site
copyright: Copyright &copy; 2026 Wijkqwe | Code：<a href="https://www.gnu.org/licenses/agpl-3.0.html" target="_blank">AGPL-3.0</a> | Docs：<a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode" target="_blank">CC BY-SA 4.0</a>


theme:
  name: material
  language: zh
  features: #: 开启功能（导航、返回顶部等）
    - content.code.annotate
    - content.code.copy #: 为代码块开启复制选项
    - navigation.tabs #: 将顶级导航部分渲染为顶部标签栏
    - navigation.indexes #: 为每个导航部分关联一个索引界面
    - navigation.top #: 返回顶部按钮
    - search.highlight #: 在搜索结果中高亮关键词
    - toc.follow
  palette: #: 颜色方案（支持亮/暗切换）
    - media: "(prefers-color-scheme: light)"
      scheme: default #: 配色方案：浅色模式
      # primary: indigo #: 原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      # accent: pink #: 强调色，默认蓝，可以交互的元素如悬停链接、按钮和滚动条
      toggle:
        icon: material/weather-sunny #: 图标，太阳
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate   #: 暗色模式
      # primary: blue
      toggle:
        icon: material/weather-night #: 图标，月亮
        name: 切换到亮色模式

extra_css:
  - css/custom.css
  - css/toc-fold.css

nav:
  - Home:
    - index.md
  - Note:
    - note/index.md
    - 编程语言:
      - C#: note/c#.md
      - C++: note/cpp.md
      - Java: note/java.md
      - Powershell: note/powershell.md
      - Python: note/python.md
      - Shell: note/shell.md
    - Browser Plugin: note/browser_plugin.md
    - Cmd: note/cmd.md
    - CSS: note/css.md
    - Gdb: note/gdb.md
    - Git: note/git.md
    - Kitty: note/kitty.md
    - Markdown: note/markdown.md
    - Npm: note/npm.md
    - Opencode: note/opencode.md
    - Pacman: note/pacman.md
    - Potpourri:
      - Daemons: note/potpourri/daemons.md
      - Data Wrangling: note/potpourri/data_wrangling.md
      - Debug: note/potpourri/debug.md
      - Keyboard: note/potpourri/keyboard.md
      - Make: note/potpourri/make.md
      - Security: note/potpourri/security.md
      - Test: note/potpourri/test.md
      - Version: note/potpourri/version.md
      - VPN: note/potpourri/VPN.md
    - Tmux: note/tmux.md
    - Tools: note/tools.md
    - Vim: note/vim.md
    - Virtualbox: note/virtualbox.md
    - Vue: note/vue.md
    # - 编译原理: note/编译原理.md
    # - 体系结构: note/体系结构.md
  - Virtual Machine:
    - Arch Linux:
      - Arch in VMWare: virtual_machine/Arch_VMware/main.md
      - Arch in Virtual: virtual_machine/Arch_VirtualBox/main.md
